apiVersion: apps/v1
kind: Deployment
metadata:
  name: itm-bce-dbw-dpl
  namespace: itm-bce-dbw-nms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: interviewmaster
  template:
    metadata:
      labels:
        app: interviewmaster
        version: v1.0.0
        tier: backend
    spec:
      containers:
      - image: jongik0217/im_post:test
        name: itm-bce-dbw
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: itm-bce-dbw-svc
  namespace: itm-bce-dbw-nms
  labels:
    app: interviewmaster
    version: v1.0
    tier: backend
spec:
  type: NodePort
  selector:
    app: interviewmaster
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30001
