apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: itm-fre-all-nms
  labels:
    app: interviewmaster
    version: v1.0.0
    tier: frontend
  name: itm-fre-all-dpl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: interviewmaster
      version: v1.0.0
      tier: frontend
  template:
    metadata:
      labels:
        app: interviewmaster
        version: v1.0.0
        tier: frontend
    spec:
      containers:
      - image: kangyejini/test:1.09
        name: itm-fre-all-pod
        ports:
        - containerPort: 3000

