apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: itm-fre-all-nms
  labels:
    app: interviewmaster
    version: v1.0.0
    tier: frontend
  name: itm-fre-all-dpl
spec:
  selector:
    matchLabels:
      app: interviewmaster
      version: v1.0.0
      tier: frontend
  template:
    metadata:
      labels:
        app: interviewmaster
        version: v1.0.0
        tier: frontend
    spec:
      containers:
      - image: kangyejini/im:7.10
        name: itm-fre-all-pod
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 200m
            memory: 100Mi
        ports:
        - containerPort: 3000
